name: push file to s3
on: workflow_dispatch
jobs:
  upload-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        uses: actions/checkout@v4

      - name: create a demo file
        run: | 
           mkdir build
           echo "this is created from GHA" > build/index.html
           
      - name: copy to s3 bucket
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export AWS_DEFAULT_LOCATION=${{ secrets.AWS_DEFAULT_REGION }}
          aws s3 cp build/index.html s3://demo-bucket-avc/

      - name: download from s3 bucket
        run: |
         aws s3 cp s3://demo-bucket-avc/index.html .
         cat index.html
           
           
          
